import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <div className="navbar bg-base-100 shadow-sm px-6">
          <div className="flex-1">
            <a href="/" className="text-xl font-bold">YourCompany</a>
          </div>
          <div className="flex gap-4">
            <a href="/services">Services</a>
            <a href="/about">About</a>
            <a href="/contact">Contact</a>
          </div>
        </div>

        <main className="min-h-screen">
          {children}
        </main>

        <footer className="footer footer-center p-6 bg-base-200">
          <p>© {new Date().getFullYear()} YourCompany</p>
        </footer>
    </body>
    </html >
  );
}
